# Generated by Django 4.1.2 on 2022-10-22 16:04

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('reference1', models.CharField(blank=True, max_length=50, null=True)),
                ('reference2', models.CharField(blank=True, max_length=50, null=True)),
                ('reference3', models.CharField(blank=True, max_length=50, null=True)),
                ('origin_address', models.TextField(blank=True, null=True)),
                ('origin_address_city', models.CharField(max_length=50)),
                ('origin_address_state_or_province_code', models.CharField(max_length=50)),
                ('origin_address_post_code', models.CharField(max_length=50)),
                ('origin_address_country_code', models.CharField(max_length=50)),
                ('destination_address', models.TextField(blank=True, null=True)),
                ('destination_address_city', models.CharField(max_length=50)),
                ('destination_address_state_or_province_code', models.CharField(max_length=50)),
                ('destination_address_post_code', models.CharField(max_length=50)),
                ('destination_address_country_code', models.CharField(max_length=50)),
                ('number_of_pieces', models.IntegerField()),
                ('actual_weight_unit', models.CharField(max_length=50)),
                ('actual_weight_value', models.CharField(max_length=50)),
                ('product_group', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=50)),
                ('width', models.FloatField()),
                ('hight', models.FloatField()),
                ('receiver_date', models.DateField()),
                ('estimated_dlivery_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.courier')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.shipmentstatus')),
            ],
        ),
    ]
