# Generated by Django 4.1.2 on 2022-10-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_shipmentstatus_counnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentstatus',
            name='counnt',
        ),
    ]
