# Generated by Django 4.1.2 on 2022-10-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
